spring.application.name=pharmaguard-api
spring.messages.basename=message

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

security.jwt.secret=UGhhcm1hR3VhcmRBUElKV1RTZWNyZXRLZXlGb3JIbWFjU2hhMjU2
security.jwt.access-token-validity-seconds=3600
security.jwt.refresh-token-validity-seconds=1209600
