-- Distribui o consumo historico do MVP no periodo recente para melhorar a leitura do grafico do dashboard.

UPDATE saidas_estoque
SET data_saida = CASE id
    WHEN 9001 THEN CURRENT_TIMESTAMP - INTERVAL '29 days'
    WHEN 9002 THEN CURRENT_TIMESTAMP - INTERVAL '24 days'
    WHEN 9003 THEN CURRENT_TIMESTAMP - INTERVAL '19 days'
    WHEN 9004 THEN CURRENT_TIMESTAMP - INTERVAL '14 days'
    WHEN 9005 THEN CURRENT_TIMESTAMP - INTERVAL '9 days'
    WHEN 9006 THEN CURRENT_TIMESTAMP - INTERVAL '4 days'
    WHEN 9007 THEN CURRENT_TIMESTAMP - INTERVAL '1 day'
    ELSE data_saida
END
WHERE id BETWEEN 9001 AND 9007;

UPDATE movimentacoes_estoque
SET data_movimentacao = CASE id
    WHEN 9008 THEN CURRENT_TIMESTAMP - INTERVAL '29 days'
    WHEN 9009 THEN CURRENT_TIMESTAMP - INTERVAL '24 days'
    WHEN 9010 THEN CURRENT_TIMESTAMP - INTERVAL '19 days'
    WHEN 9011 THEN CURRENT_TIMESTAMP - INTERVAL '14 days'
    WHEN 9012 THEN CURRENT_TIMESTAMP - INTERVAL '9 days'
    WHEN 9013 THEN CURRENT_TIMESTAMP - INTERVAL '4 days'
    WHEN 9014 THEN CURRENT_TIMESTAMP - INTERVAL '1 day'
    ELSE data_movimentacao
END
WHERE id BETWEEN 9008 AND 9014;